name: E2E Test

on: [push, pull_request]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Robot Framework chrome
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          robot_threads: 2
          robot_tests_dir: test/postnord
          robot_reports_dir: reports
          browser: 'chrome'
          
      - name: Robot Framework firefox
        uses: joonvena/robotframework-docker-action@v1.0
        with:
          robot_threads: 2
          robot_tests_dir: test/postnord
          robot_reports_dir: reports
          browser: 'firefox'
          
      - name: Upload product test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: e2e-test-report
          path: reports
